### ISSUE TITLE
Improve UX of imagelab.report() when running python from terminal

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanvision#135]
Currently, matplotlib opens a new window for each plot, but it does not open them all simultaneously. So Terminal users have to manually exit from each window one at a time and it is quite cumbersome to get through the report.

**Comment by addison-ch** [comment]
Would a better approach be to open each plot immediately and leave them open indefinitely? Should we concerned about there being too many windows popping up then?

**Comment by sanjanag** [comment]
You could modify it to behave like this:

All the figures open simultaneously when you call `imagelab.report()`. This makes it less painful to go through the report. Too many windows wouldn't be a concern when showing output for `imagelab.report()` as there are maximum 8 issue types.
The user can move to subsequent code by quitting these windows.

To make it clear which plots belong to which issue types, you can also consider adding a title to each figure that says which issue type is shown in those examples.

**Comment by sanjanag** [comment]
Closing as this is the intended behvaior for now and would require a big revamp of visualization when running through terminal
