### ISSUE TITLE
Files loaded twice when image folder has images with .jpeg or .png extensions. 

### ISSUE THREAD

**Issue by GirinChutia** [cleanlab/cleanvision#141]
# Files loaded twice when image folder has images with .jpeg or .png extensions. 

When files in the image folder are of .jpeg and .png. Images are loaded twice. Below is a screenshot where I have shown the output from Imagelab and glob.

![image](https://user-images.githubusercontent.com/71626493/228602195-2a5c1d19-51b7-4f78-9bad-cee5764f497b.png)

**Comment by jwmueller** [comment]
@GirinChutia  Thank you for the bug report!  

Could you share the full list of 6 filenames? And your full script to reproduce the issue?
