### ISSUE TITLE
Is there GPU acceleration for large datasets?

### ISSUE THREAD

**Issue by felipe-parodi** [cleanlab/cleanvision#148]
Can't seem to find something on this, but is there or will there be functionality for GPU acceleration? Thanks!

**Comment by sanjanag** [comment]
Hi @felipe-parodi! CleanVision is built in a way that it can run on large datasets only using CPUs in a reasonable time. But there is room for further scaling the current package via embarrasingly parallel implementation. For example, one can split images in a dataset across a bunch of multicore machines, run cleanvision separately on each of the splits, merge the results which are just pandas dataframes. The package does not do any compute intensive tasks training so there is no requirement for GPU acceleration as yet. 

Could you tell more about your requirements like the size of your dataset on which you're trying to run cleanvision?

**Comment by felipe-parodi** [comment]
Hi @sanjanag! actually i tried running cleanvision during another process so my cores were all taken up. it does work relatively fast (on a ~50-200k img dataset) otherwise-- thank you!
