### ISSUE TITLE
Support for large-scale datasets on the cloud

### ISSUE THREAD

**Issue by LemurPwned** [cleanlab/cleanvision#149]
Hey,
first of all thanks for the great tool :) 

I think, it would be nice if the image reading capacity would be extended to non-local paths e.g. paths exposed via [`fsspec`-like interface types](https://filesystem-spec.readthedocs.io/en/latest/).

# Details
* Code/Notebooks running on the cloud could have easy access to the dataset which "looks" local without having to mount it explicitly.
For instance, in the function [`compute_scores`](https://github.com/cleanlab/cleanvision/blob/7f6b695f1371e91d163cb2349cc07a6c862da42a/src/cleanvision/issue_managers/image_property_issue_manager.py#L31):
```python
def compute_scores(
    fs: fsspec.spec.AbstractFileSystem, 
    path: str, to_compute: List[str], properties: Dict[str, ImageProperty]
) -> Dict[str, Any]:
    # image = Image.open(path) # this only opens local, not even a signed url
    with fs.open(path) as f:
        image = Image.open(f)
    results: Dict[str, Any] = {}
    results["path"] = path
    for issue_type in to_compute:
        results = {**results, **properties[issue_type].calculate(image)}
    return results
```
* Currently, for a large dataset, it needs to be either downloaded beforehand or directly mounted in the FS system.
* Could be super handy for large-scale unsupervised datasets.

**Comment by jwmueller** [comment]
Great suggestion @LemurPwned !
Might you be interested in helping us implement this?

**Comment by LemurPwned** [comment]
@jwmueller sure, I'll sketch something out :)

**Comment by jwmueller** [comment]
Awesome! I am confident this would be super useful

**Comment by jwmueller** [comment]
Related request from the [Cleanlab Community Slack](https://cleanlab-community.slack.com/archives/C03ENS0QQHJ/p1684028943984449?thread_ts=1683931381.099539&cid=C03ENS0QQHJ):    

Pass in a list of urls to images and run CleanVision

**Comment by jwmueller** [comment]
Completed in https://github.com/cleanlab/cleanvision/pull/176
