### ISSUE TITLE
Torch data loaders interfere with cleanvision parallelization

### ISSUE THREAD

**Issue by sanjanag** [cleanlab/cleanvision#155]
Need to set n_job=1 right now, otherwise the code runs super slow.

**Comment by jwmueller** [comment]
Easy solution for now:

in find_issues(): if the provided dataset was torch dataset and n_jobs = None, then just default n_jobs = 1

**Comment by jwmueller** [comment]
After fixing this, remember to remove the `n_jobs = 1` argument currently passed for all the torch dataset examples/tutorials
