### ISSUE TITLE
Share a list of images that had the issues mentioned

### ISSUE THREAD

**Issue by PraneethaB22** [cleanlab/cleanvision#172]

**Comment by jwmueller** [comment]
Hi @PraneethaB22 have you gone through our quickstart tutorial?
https://github.com/cleanlab/cleanvision-examples/blob/main/tutorial.ipynb

It shows you have how to see which images are exhibiting each issue. Specifically this is stored in the `imagelab.issues` attribute.

For example here's how to see the blurry images, sorted by the severity of the issue:
```
blurry_images = imagelab.issues[imagelab.issues["is_blurry_issue"] == True].sort_values(by=['blurry_score'])
blurry_image_files = blurry_images.index.tolist()
imagelab.visualize(image_files=blurry_image_files)
```
