### ISSUE TITLE
Images with a `*.JPG` extension are missed

### ISSUE THREAD

**Issue by stefanistrate** [cleanlab/cleanvision#197]
Cleanvision should consider all extensions from [here](https://github.com/cleanlab/cleanvision/blob/main/src/cleanvision/utils/constants.py#L22-L32) irrespective of the letter case. I currently have a folder of images with the `*.JPG` extension and Cleanvision misses them all.

# Steps to reproduce

Create a folder with a couple of images with a `*.JPG` extension and run the following:

```python
from cleanvision import Imagelab
imagelab = Imagelab(data_path="path_to_folder")
imagelab.find_issues()
```

# Additional information

- **CleanVision version**: 0.3.0 
- **Operating system**: macOS 13.3.1 
- **Python version**: 3.10.11

**Comment by jwmueller** [comment]
@stefanistrate Thanks for reporting this issue!  Agree CleanVision should work across the supported file extensions regardless of their letter case. There was previously some trickiness to ensuring proper behavior across Windows + other OS.

Got any specific code fixes you suggest?  PRs are always welcome 😄  

And for your use-case, I believe you should still be able to run [Imagelab](https://cleanvision.readthedocs.io/en/latest/cleanvision/imagelab.html) with the `filepaths` argument instead?

**Comment by stefanistrate** [comment]
`filepaths` could work in my case, although if I have nested directories it becomes the same problem of listing all image files efficiently. What I could recommend instead, in terms of implementation, is to call `glob.glob()` just once to list all files, then split the extension from each of them and finally match its lowercase version against a set of allowed extensions. This would also have the advantage of not needing to de-duplicate items on Windows.

**Comment by foskyblue** [comment]
in this case, if we just include the extension ".JPG" in the constants then glob should be able to find these files. No?

**Comment by stefanistrate** [comment]
Yes, that's correct.

**Comment by jwmueller** [comment]
should be closed by: https://github.com/cleanlab/cleanvision/pull/200
Feel free to re-open the issue if you still have problems with developer versions of cleanvision or after next stable release
