### ISSUE TITLE
Unit test for truncate title in case the title is too long in visualization

### ISSUE THREAD

**Issue by sanjanag** [cleanlab/cleanvision#223]
Test the title string is truncated appropriately when the title width exceeds cell width. Specifically test [truncate_titles()](https://github.com/cleanlab/cleanvision/blob/6cf3c7baa8312baa05c23e96a2bcd98d7d4376eb/src/cleanvision/utils/viz_manager.py#L40) method. The test for this should go here https://github.com/cleanlab/cleanvision/blob/main/tests/test_viz_manager.py

**Comment by aenlemmea** [comment]
Can this be assigned to me?

**Comment by sanjanag** [comment]
Sure, feel free to raise a PR!
