### ISSUE TITLE
`psutils` and `s3fs` not installed errors

### ISSUE THREAD

**Issue by smttsp** [cleanlab/cleanvision#224]
https://github.com/cleanlab/cleanvision/blob/6cf3c7baa8312baa05c23e96a2bcd98d7d4376eb/requirements-dev.txt#L12

After the installation as shown here: https://github.com/cleanlab/cleanvision/blob/main/DEVELOPMENT.md#installing-dependencies-and-cleanvision-package, I ran pytest which resulted in the following errors: 

```
______________________________________________________________ ERROR collecting tests/test_utils.py ______________________________________________________________
ImportError while importing test module '/Users/samet/Documents/codes/cleanlab/cleanvision/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_utils.py:5: in <module>
    import psutil
E   ModuleNotFoundError: No module named 'psutil'
=
```

and 

```
E               ImportError: Install s3fs to access S3

ENV/lib/python3.9/site-packages/fsspec/registry.py:228: ImportError
======================================================================== warnings summary ========================================================================
ENV/lib/python3.9/site-packages/urllib3/__init__.py:34
  /cleanlab/cleanvision/ENV/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================================================== short test summary info =====================================================================
FAILED tests/test_run.py::test_s3_dataset - ImportError: Install s3fs to access S3
=
```

Once I install both of them, `pytest` worked out fine.

**Comment by smttsp** [comment]
To be honest, I would recommend switching to `poetry` + `direnv` + `pyenv` instead of `pip install`. To my experience, it is so much more convenient. 

Here is installation guide I created in one of my repos: https://github.com/smttsp/temporal_consistency_odt#installation

**Comment by jwmueller** [comment]
Thanks for reporting this!
@sanjanag Can you update: https://github.com/cleanlab/cleanvision/blob/main/DEVELOPMENT.md#installing-dependencies-and-cleanvision-package

to install cleanvision locally with all of the optional dependencies too?

**Comment by sanjanag** [comment]
Hi @smttsp ! Thanks for pointing this out. This PR https://github.com/cleanlab/cleanvision/pull/225 should resolve this

**Comment by smttsp** [comment]
@sanjanag Great!
