### ISSUE TITLE
Ensure library is compatible with deep learning packages

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanvision#38]
Make sure the library can be installed with many versions of:
- [ ] pytorch
- [ ] pytorch-lightning
- [ ] tensorflow
- [ ] huggingface
- [ ] timm
- [ ] jax

**Comment by Acedev003** [comment]
Hi @jwmueller. I would like to contribute in solving this particular issue. Could you please give some additional guidelines on the tasks to be completed.

**Comment by sanjanag** [comment]
Hi @Acedev003 ! This issue has been resolved by a recent PR.
Are there any other [issues](https://github.com/cleanlab/cleanvision/issues) that look interesting to you for contribution ?

Here are a few interesting ones that you could start with and would also help in knowing the codebase.
https://github.com/cleanlab/cleanvision/issues/130
https://github.com/cleanlab/cleanvision/issues/124

Let me know what interests you and I can help with answering any further questions related to that.

**Comment by Acedev003** [comment]
I think I'll go ahead with issue #124. 
Please do provide more insights into this. Should the conversion be continued in that particular thread? 
Thanks.

**Comment by sanjanag** [comment]
Yes, it would be more appropriate to move the discussion to that thread.

**Comment by sanjanag** [comment]
I've added more details on the issue in the relevant thread. Feel free to ask more questions there.

**Comment by jwmueller** [comment]
closed by: https://github.com/cleanlab/cleanvision/pull/145
