### ISSUE TITLE
Add flake8 to pre-commit hooks

### ISSUE THREAD

**Issue by sanjanag** [cleanlab/cleanvision#90]

**Comment by Kadam-Tushar** [comment]
Hi, 
I am trying to add flake8 to pre-commit hooks. After running `flake8` with default arguments, I see many long lines of code (> 79 chars). 

What configuration of flake8 are we planning to use for a pre-commit hook?

**Comment by sanjanag** [comment]
`flake8 --ignore=E501,E722,E401,W503 src tests --count --show-source --statistics`
in https://github.com/cleanlab/cleanvision/blob/main/.github/workflows/ci.yml

**Comment by manulpatel** [comment]
Hello @sanjanag! Is someone currently working on this? I would be happy to contribute.

**Comment by sanjanag** [comment]
Hi @manulpatel ! Great to see your interest in the package. Yeah, you can go ahead and submit a PR for this issue.
